### PR TITLE
ix: remove force

### PR DESCRIPTION
**Pull request by sakulstra**
I don't see a good reason on why one would want to rebuld via `--force` ignoring all caches.
In bigger foundry projects this can take a decent amount of time.
Therefore I'm removing the "force" - if you have strong feelings about keeping it i guess it could be an option to enable/disable via cli flag.

### CODE REVIEW

**Comment by kartojal** [comment]
Unfornately if you don't use `--force` and there is no changes, `forge` will not generate the `build-info` artifacts.

```
$ forge build --build-info
[⠔] Compiling...
No files changed, compilation skipped
Compilation successful

[catapulta-verify] Exiting main handler, error:
ENOENT: No such file or directory
   path: "out/build-info"
 syscall: "open"
   errno: -2
   ```

**Comment by kartojal** [comment]
i could add an "skip --force" param, but must only be used if you already did `--build-info --force` before, to prevent multiple `forced` builds

**Comment by sakulstra** [comment]
I think it would be better to do it conditionally if the required files don't yet exist.

**Comment by kartojal** [comment]
i will implement your idea to detect if build-info exists to skip the --force build in consequent verifications

**Comment by sakulstra** [comment]
Seems like the original issue holding this back was resolved in https://github.com/foundry-rs/foundry/pull/7347

**Pull request closed without merging**
